### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by BeardlyBard** [AstianBK/IllagerRevolution#2]
I am trying to play this mod with my son. He uses a controller and we play on the same computer. However, whenever I install any controller mod (ie. controllable/controller support mod) the game will not load. I have the log from Modrinth. Any help would be appreciated.

https://mclo.gs/6cMjs3W

**Comment by AstianBK** [comment]
What you sent me only says that you're missiong a library called "unionlib" for the controller mod and that it requires version 10.1.1 not 10.2.2, nothing regarding Illager Revolution, i hope that helps!

**Comment by BeardlyBard** [comment]
Awesome! Thank you so much. I don't know how I missed that. Still learning how to read those logs. My son will be so happy to play this mod later. Thank you for all your hard work on this mod.
