### ISSUE TITLE
I have a problem with the game while launching this mod

### ISSUE THREAD

**Issue by PlanetGalaxy2008** [AstianBK/IllagerRevolution#3]
Hello, it seems that i have an issue that when i launch the game while using this mod. The mod used to work pretty much normal but the game for unknown reasons now refuses to start, i did not touch anything or something like that, are you gonna try to fix this issue anytime soon?
![bandicam2024-01-3109-59-56-300-ezgif com-video-to-gif-converter](https://github.com/AstianBK/IllagerRevolution/assets/106810679/1875b2f7-6fe2-4ec0-ad4c-f06004ee20d1)

**Comment by AstianBK** [comment]
Can you please send a crash report? I cant really tell whats happening from the video alone

**Comment by PlanetGalaxy2008** [comment]
> Can you please send a crash report? I cant really tell whats happening from the video alone

i dont get a crash report for some reason but the mod is working again so i think my pc was acting up ig

**Comment by AstianBK** [comment]
Glad to hear it works, must've been your pc then.
